[2024-08-09T08:28:46.002+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-09T08:28:46.042+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_postgresql.etl_task manual__2024-08-09T08:28:41.097888+00:00 [queued]>
[2024-08-09T08:28:46.059+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_postgresql.etl_task manual__2024-08-09T08:28:41.097888+00:00 [queued]>
[2024-08-09T08:28:46.060+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-09T08:28:46.084+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): etl_task> on 2024-08-09 08:28:41.097888+00:00
[2024-08-09T08:28:46.097+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1357) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-09T08:28:46.098+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_postgresql', 'etl_task', 'manual__2024-08-09T08:28:41.097888+00:00', '--job-id', '200', '--raw', '--subdir', 'DAGS_FOLDER/etl_v1.py', '--cfg-path', '/tmp/tmp0g5vq7hc']
[2024-08-09T08:28:46.101+0000] {standard_task_runner.py:64} INFO - Started process 1366 to run task
[2024-08-09T08:28:46.102+0000] {standard_task_runner.py:91} INFO - Job 200: Subtask etl_task
[2024-08-09T08:28:46.173+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_postgresql.etl_task manual__2024-08-09T08:28:41.097888+00:00 [running]> on host c6a41f5817de
[2024-08-09T08:28:46.308+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_postgresql' AIRFLOW_CTX_TASK_ID='etl_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-09T08:28:41.097888+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-09T08:28:41.097888+00:00'
[2024-08-09T08:28:46.313+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-09T08:28:46.333+0000] {logging_mixin.py:188} INFO - ETL process completed successfully!
[2024-08-09T08:28:46.334+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-09T08:28:46.336+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-09T08:28:46.352+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_postgresql, task_id=etl_task, run_id=manual__2024-08-09T08:28:41.097888+00:00, execution_date=20240809T082841, start_date=20240809T082846, end_date=20240809T082846
[2024-08-09T08:28:46.400+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-08-09T08:28:46.424+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-09T08:28:46.429+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
